#161967125 add descriptive signup/registration validation errors.
andela/ah-code-titans pull request #10
Opened 2018-12-05 12:55 UTC by jillo-abdullahi

**What does this PR do?**

Update user registration validations and update validation errors.

**Description of tasks to be completed**

1. Add username validation for the following invalid inputs:

- Username length being less than 4 characters.
- Username having numbers only.

2. Add password validation for the following invalid inputs:
   

- Password length being less than 8.
- Password not containing at least one number.
- Password not containing at least one uppercase character.
- Password not containing at least one lowercase character.
- Password not containing at least one special character.

3. Add email validations error messages for duplicate email registration.
4. Update tests to cater for new validation error messages.

**How should this be manually tested?**

Clone the repo from your terminal: `git clone https://github.com/andela/ah-code-titans.git`

Create a virtual environment:`python3 -m venv <name_of_environment>`

Activate the virtual environment:  `source <name_of_environment>/bin/activate`

Install project dependencies: `pip install -r requirements.txt`

Add the following environment variables and populate them with your settings:

-`$ export DB_NAME='choose_a_dbname'`
-`$ export DB_USER='db_username'`
-`$ export DB_PASSWORD='db_role_password'`
-`$ export DB_HOST='localhost or preffered host'`
-`$ export DB_PORT='server_port_number'`
-`$ export SECRET_KEY='your_secret_key'`

Switch to the appropriate branch: `git checkout ft-validate-signup-161967125`
Run migrations: `python manage.py migrate`
Run tests: `python manage.py test`

**What are the relevant Pivotal Tracker stories?**
[#161967125](https://www.pivotaltracker.com/story/show/161967125)

**Checklist**

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [x] I have commented my code, particularly in hard-to-understand areas

- [x] I have made corresponding changes to the documentation

- [x] My changes generate no new warnings

2018-12-05 14:14 UTC, Darius-Ndubi requested changes

2018-12-05 14:14 UTC, Darius-Ndubi commented on authors/settings.py
> +  'SHOW_REQUEST_HEADERS': True,
This should not be changed, check indentation spaces

2018-12-05 14:26 UTC, jillo-abdullahi commented on authors/settings.py
> +  'SHOW_REQUEST_HEADERS': True,
Thanks for noticing @Darius-Ndubi. I have updated this file.

2018-12-05 14:26 UTC, Darius-Ndubi approved these changes

2018-12-05 15:19 UTC, Bryan-Cee approved these changes
👍

2018-12-05 15:29 UTC, davishooly approved these changes

2018-12-05 17:39 UTC, mutoromike requested changes
Kindly add tests for the invalid user registration outcomes.

2018-12-06 07:30 UTC, mutoromike commented
Also, fix the merge conflicts.

2018-12-06 08:38 UTC, mutoromike approved these changes

2018-12-06 09:05 UTC, merged