#161967126 Ft registration email verification
andela/ah-code-titans pull request #13
Opened 2018-12-06 07:05 UTC by Bryan-Cee

**What does this PR do?**

Enable email verification upon registration.

**Description of tasks to be completed**

- Add email verification upon registration.
- Fixed errors raised by Flake8
- Add tests for email verification
- Refactor failing test

**How should this be manually tested?**

Clone the repo from your terminal: `$ git clone https://github.com/andela/ah-code-titans.git
`
Create a virtual environment: `$ python3 -m venv <name_of_environment>`

Activate the virtual environment: `$ source <name_of_environment>/bin/activate`

Install project dependencies: `$ pip install -r requirements.txt`

Add the following environment variables and populate them with your settings:

-`$ export DB_NAME='choose_a_dbname'`
-`$ export DB_USER='db_username'`
-`$ export DB_PASSWORD='db_role_password`'
-`$ export DB_HOST='localhost or preffered host'`
-`$ export DB_PORT='server_port_number'`
-`$ export SECRET_KEY='your_secret_key'`

Switch to the appropriate branch: `$ git checkout ft-registration-email-verification-161967126`
Run migrations: `$ python manage.py migrate`
Run tests: `$ python manage.py test`

What are the relevant Pivotal Tracker stories?
[#161967126](https://www.pivotaltracker.com/story/show/161967126)

Checklist

- [x]   My code follows the style guidelines of this project 
- [x]   I have performed a self-review of my own code
- [x]   I have commented my code, particularly in hard-to-understand areas
- [x]   I have made corresponding changes to the documentation
- [x]   My changes generate no new warnings

Screenshots
<img width="661" alt="screenshot 2018-12-06 at 10 04 19" src="https://user-images.githubusercontent.com/19145546/49567314-5be7b300-f93e-11e8-8dce-28269f0b2ecb.png">

2018-12-06 09:41 UTC, jillo-abdullahi requested changes
`test_login_with_inactive_account` is failing locally. There could be an env variable you have not added here.

2018-12-06 09:53 UTC, jillo-abdullahi commented
@Bryan-Cee You can rebase to develop to pick up @davishooly's changes and try re-running your tests.

2018-12-06 10:09 UTC, jillo-abdullahi approved these changes

2018-12-06 10:18 UTC, davishooly approved these changes

2018-12-06 12:42 UTC, denomash commented on authors/apps/authentication/tests/test_login.py
>          """ test login success """
update this comment to match the function of the test

2018-12-06 13:37 UTC, Darius-Ndubi approved these changes
👍

2018-12-06 14:22 UTC, denomash approved these changes
👍

2018-12-07 07:17 UTC, bettblake08 requested changes

2018-12-07 07:17 UTC, bettblake08 commented on authors/apps/authentication/tests/test_register.py
> +        from django.utils.encoding import force_bytes
Please move the import to the top.

2018-12-07 07:44 UTC, mutoromike requested changes
Kindly add the register screenshot.

2018-12-07 08:30 UTC, bettblake08 reviewed
Response message should inform the user check their email.

2018-12-07 08:37 UTC, bettblake08 approved these changes
👍 Looks good!

2018-12-07 09:28 UTC, mutoromike approved these changes

2018-12-07 09:29 UTC, merged