#161967131 User should be able to rate article and view article rating
andela/ah-code-titans pull request #19
Opened 2018-12-13 15:06 UTC by Darius-Ndubi

## What does this PR do?
 Allow authenticated users to rate an article.
 Allow any user to view an article's rating.

## Description of tasks to be completed  
 - Add feature to allow *only* authenticated users to rate an article and edit their previous rating.
 - Add feature to retrieve the rating of a particular article.
 - Add tests on the features above.

## How should this be manually tested
 - Clone the repo from your terminal: `git clone https://github.com/andela/ah-code-titans.git`
 - Create a virtual environment:`python3 -m venv <name_of_environment>`
 - Activate the virtual environment:  `source <name_of_environment>/bin/activate`
 - Install project dependencies: `pip install -r requirements.txt`
- Add the following environment variables and populate them with your settings:
  - `export DB_NAME='choose_a_dbname'`
  - `export DB_USER='db_username'`
  - `export DB_PASSWORD='db_role_password'`
  - `export DB_HOST='localhost or preffered host'`
  - `export DB_PORT='server_port_number'`
  - `export SECRET_KEY='your_secret_key'`
  - `export EMAIL_HOST_USER="codetitans32@gmail.com"`
  - `export EMAIL_HOST_PASSWORD='Codetitans@32'`
- Switch to branch `ft-rate-article-161967131`
- Run migrations by:
    -  `python manage.py makemigrations`
    - `python manage.py migrate`
- Run tests by:
    - `python manage.py test`

## What are the relevat Pivotal tracker stories
[#161967131](https://www.pivotaltracker.com/story/show/161967131)

## Checklist

- [ ] My code follows the style guidelines of this project

- [ ] I have performed a self-review of my own code

- [ ] I have commented my code, particularly in hard-to-understand areas

- [ ] I have made corresponding changes to the documentation

- [ ] My changes generate no new warnings

## Screenshots

2018-12-13 16:25 UTC, mutoromike requested changes
Consider refactoring the methods used in the tests. You can have them in one file instead of them repeating.

2018-12-13 16:25 UTC, mutoromike commented on authors/apps/rating/tests/test_rate_get.py
> +    def email_verification_and_login_user2(self):
Consider refactoring these three methods. They are in two files.

2018-12-13 16:26 UTC, Darius-Ndubi commented on authors/apps/rating/tests/test_rate_get.py
> +    def email_verification_and_login_user2(self):
okay @mutoromike  let me work on that

2018-12-13 17:29 UTC, Darius-Ndubi commented on authors/apps/rating/tests/test_rate_get.py
> +    def email_verification_and_login_user2(self):
@mutoromike the changes have been made. thank you.

2018-12-14 07:41 UTC, denomash approved these changes
👍

2018-12-14 07:56 UTC, davishooly approved these changes

2018-12-15 12:51 UTC, mutoromike approved these changes

2018-12-15 12:51 UTC, merged