#161967118 Integrate Travis CI
andela/ah-code-titans pull request #2
Opened 2018-11-26 17:36 UTC by Darius-Ndubi

#### Resolves #161967118 
----------

#### Description
  - Intergrates Travis with Authors Haven Django app.
  - Adds a badge for the builds on the readme.
------------
#### Type of change
- [ ] This change requires a documentation update
------------
#### How has this been tested?
No tests required
------------

#### Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2018-11-27 07:19 UTC, jillo-abdullahi commented
@Darius-Ndubi Are the checklists under **Type of Change** from the template supposed to act as a guide or should they also be on the actual PR? @mutoromike

2018-11-27 08:08 UTC, Darius-Ndubi commented
I am working to create a template on the PR format to integrate the two and ask if its okay to use it.

2018-11-27 08:10 UTC, bettblake08 commented
@darius I believe all is good with the PR. The structure of the PR still needs to be improved on to meet the Andela conventions.

2018-11-27 08:13 UTC, mutoromike commented
I think the PR is okay, and also the commits match the engineering playbook requirements. For PRs, we will be using the PR format suggested by @evansmusomi, this was previously shared.

2018-11-28 05:49 UTC, mutoromike requested changes
The Travis Badge is not working, even on your branch. Kindly fix it.

2018-11-28 06:25 UTC, bettblake08 reviewed
The PR is all good.

2018-11-28 08:50 UTC, Darius-Ndubi commented
@mutoromike the conflicts have been solved, thank you for the feedback.

2018-11-28 09:18 UTC, Bryan-Cee commented on .coveralls.yml
> +repo_token: BQg4BzLvHTeY9Rb96xVCSHqY2iEFoJatm
Please add a new line to this file to act as the EOL.

2018-11-28 09:23 UTC, Bryan-Cee requested changes

2018-11-28 09:23 UTC, Bryan-Cee commented on .coveralls.yml
> +repo_token: BQg4BzLvHTeY9Rb96xVCSHqY2iEFoJatm
Please add a new line at the end of this file as the EOL.

2018-11-28 09:26 UTC, davishooly commented
@Darius-Ndubi concerning the coveralls badge its still pointing to master branch it should point to develop

2018-11-28 09:35 UTC, mutoromike approved these changes

2018-11-28 14:53 UTC, closed without merging