161967141 Add Search Functionality and Custom filtering based on parameters
andela/ah-code-titans pull request #31
Opened 2018-12-19 16:24 UTC by jillo-abdullahi

**What does this PR do?**
-  Implement search functionality and custom filtering based on parameters.

**Description of Task to be completed?**
- Add article search by title and author using keywords.
- Implement filters for title and author on all articles
- Implement filtering of articles using tags.

**How should this be manually tested?**

- Clone the repo and cd into the project folder
- Create a virtual environment by running `python3 -m venv <name_of_environment>`
- Activate the virtual environment by running `source <name_of_environment>/bin/activate`
- Run `$ pip install -r requirements.txt`
- Then add the following environment variables to your computer:

 - `$ export DB_NAME='choose_a_dbname'`
 - `$ export DB_USER='db_username'`
 - `$ export DB_PASSWORD='db_role_password'`
 - `$ export DB_HOST='localhost or preffered host'`
 - `$ export DB_PORT='server_port_number'`
- `$ export SECRET_KEY='some_secret_key`
- `$ export SOCIAL_AUTH_FACEBOOK_KEY='<facebook_app_id>'`
- `$ export SOCIAL_AUTH_FACEBOOK_SECRET='<facebook_app_secret>'`
- `$ export SOCIAL_AUTH_TWITTER_KEY='<twitter_api_key>'`
- `$ export SOCIAL_AUTH_TWITTER_SECRET='<twitter_api_secret>'`
- `$ export SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='<google_client_id>'`
- `$ export SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='<google_client_secret>'`

- Change the current branch by running `git checkout ft-search-filter-161967141`
- Run `python3 manage.py makemigrations` then, `python3 manage.py migrate`
- Run tests with `python3 manage.py test`
- Run the server with `python3 manage.py runserver`

**What are the relevant pivotal tracker stories?**
- [#161967141](https://www.pivotaltracker.com/story/show/161967141)

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

**Screenshots**

<img width="1280" alt="screenshot 2018-12-19 at 19 20 57" src="https://user-images.githubusercontent.com/25426934/50232978-73558000-03c3-11e9-8997-8353d9e7cfd2.png">

<img width="1280" alt="screenshot 2018-12-19 at 19 21 23" src="https://user-images.githubusercontent.com/25426934/50232993-7d777e80-03c3-11e9-9d64-8158d9c22b78.png">

<img width="1280" alt="screenshot 2018-12-19 at 19 21 49" src="https://user-images.githubusercontent.com/25426934/50232994-7e101500-03c3-11e9-9ef1-4e486cfd8053.png">

2018-12-20 11:17 UTC, jillo-abdullahi commented
@mutoromike @bettblake08 @Bryan-Cee @denomash @Darius-Ndubi @davishooly Hi team, you must have noticed that this PR was closed and then re-opened. I fixed several conflicts with the base branch locally but ended up with a Psycopg2 connection error when running tests whose source I could not trace. I opted to delete my local branch and re-create it off develop. I then added my original files and pushed to the remote branch. I did not expect this to close the PR as the remote branch was untouched. But the PR is now live and you can go ahead and review it. Thanks.

2018-12-20 11:22 UTC, Bryan-Cee commented
I believe it would be good to have absolute imports than relative ones

2018-12-20 11:24 UTC, Bryan-Cee commented
Update your screenshots on the PR.

2018-12-20 11:29 UTC, Bryan-Cee requested changes
Please check on all your imports and make them absolute for best practice.

2018-12-20 11:35 UTC, jillo-abdullahi commented
@Bryan-Cee I have updated the screenshots. Thanks.

2018-12-20 12:18 UTC, Bryan-Cee approved these changes

2018-12-20 12:18 UTC, jillo-abdullahi commented
@Bryan-Cee I have updated the relevant imports to absolute. Thanks for the recommendation.

2018-12-20 12:24 UTC, bettblake08 requested changes

2018-12-20 12:24 UTC, bettblake08 commented on authors/apps/articles/views/filters.py
> +            return queryset.filter(tag_list__name__contains=tag_list[0])
Can you change this line of code to accommodate a list of tags?

2018-12-20 12:56 UTC, Darius-Ndubi approved these changes
👍

2018-12-20 13:41 UTC, jillo-abdullahi commented on authors/apps/articles/views/filters.py
> +            return queryset.filter(tag_list__name__contains=tag_list[0])
@bettblake08 This has been updated. Thanks

2018-12-20 13:42 UTC, bettblake08 approved these changes

2018-12-21 07:19 UTC, mutoromike approved these changes
LGTM

2018-12-21 07:20 UTC, merged