#161967123 Implement JWT token authentication
andela/ah-code-titans pull request #9
Opened 2018-12-05 06:05 UTC by davishooly

### What does this PR do?
  - Add JWT-authentication to Authors Haven Django App
<hr>

### Description of Task to be completed?
  - Add token to user registration response
  - Add token to user login response
 
<hr>

### How should this be manually tested?
 - Clone the repo and cd into the project folder
 - Create a virtual environment by running `$ python3 -m venv <name_of_environment>`
 - Activate the virtual environment by running `source <name_of_environment>/bin/activate`
 - Run `$ pip install -r requirements.txt`
 - Then add the following environment variables to your computer.

    -`$ export DB_NAME='choose_a_dbname'`
       -`$ export DB_USER='db_username'`
       -`$ export DB_PASSWORD='db_role_password'`
       -`$ export DB_HOST='localhost or preffered host'`
       -`$ export DB_PORT='server_port_number'`

- Change the current branch to ft-jwt-authentication-161967123
- Run `$ python manage.py runserver`
<hr>

### What are the relevant pivotal tracker stories?
[ #161967123 ](https://www.pivotaltracker.com/story/show/161967123)
<hr>

#### Checklist
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings

2018-12-05 06:50 UTC, bettblake08 requested changes

2018-12-05 06:50 UTC, bettblake08 commented on authors/apps/authentication/tests/test_register.py
>          )
Add a test for the access_token variable in the response body.

2018-12-05 06:50 UTC, bettblake08 commented on authors/apps/authentication/tests/test_login.py
>          response = self.login(self.user)
Add a test for the access_token in the response body.

2018-12-05 07:25 UTC, davishooly commented on authors/apps/authentication/tests/test_register.py
>          )
okay am working on that

2018-12-05 07:28 UTC, bettblake08 approved these changes
Looks good to me!

2018-12-05 13:42 UTC, mutoromike commented
Kindly attach screenshots from Postman.

2018-12-05 13:45 UTC, Darius-Ndubi requested changes
On the PR you have left us hanging. Your PR implements JWT but running python manage.py runserver does not test the functionality being added. Add more steps to how one can test the feature manually. Add screenshots too.

2018-12-05 13:45 UTC, Darius-Ndubi commented on authors/apps/authentication/backends.py
>  #
Style this imports by removing the unused ilines having '#'

2018-12-05 14:10 UTC, jillo-abdullahi approved these changes
Please add options to do migrations before running the server and let testers know that they need to try to create a new user from postman to verify if this works. Otherwise, the actual JWT implementation looks good to me.

2018-12-05 15:08 UTC, davishooly commented
> Kindly attach screenshots from Postman.

2018-12-05 15:09 UTC, davishooly commented on authors/apps/authentication/backends.py
>  #
cool @Darius-Ndubi

2018-12-05 15:13 UTC, Darius-Ndubi approved these changes

2018-12-05 15:18 UTC, davishooly commented
@mutoromikeI have done the changes requested

2018-12-05 17:54 UTC, mutoromike requested changes
Attach a screenshot of the JSON data (i.e. Postman) that's posted when creating a user or when logging in.

2018-12-06 04:11 UTC, denomash approved these changes
works fine

2018-12-06 06:45 UTC, davishooly commented
@mutoromike  cool mike

2018-12-06 06:56 UTC, davishooly commented
@mutoromike I have added the screenshot for the JSON data

2018-12-06 07:21 UTC, mutoromike approved these changes

2018-12-06 07:29 UTC, merged